apiVersion: v1
data:
  V1__Create_directors_table.sql: |-
    CREATE TABLE directors (
        id serial PRIMARY KEY,
        name varchar(100) NOT NULL
    )
  V2__Create_movies_table.sql: |-
    CREATE TABLE movies(
        id serial PRIMARY KEY,
        title varchar(150) NOT NULL,
        year int NOT NULL,
        description text,
        director_id integer,
        constraint fk_movies_directors
            foreign key (director_id)
            REFERENCES directors(id)
    )
  V3__Add_directors.sql: |
    insert into directors(name) values('Cristopher Nolan');
    insert into directors(name) values('Greta Gerwig');
  V4__Add_movies.sql: |
    insert into movies(title, year, director_id, description) values('Oppenheimer', 2023, 1, 'Epic Movie about the father of A-Bomb');
    insert into movies(title, year, director_id, description) values('Barbie', 2023, 2, 'Comedy and Musical on the popular doll');
kind: ConfigMap
metadata:
  creationTimestamp: null
  name: migration-config
